### ISSUE TITLE
currently not running correctly?

### ISSUE THREAD

**Issue by miangoar** [leandroradusky/pyFoldX#1]
Hi Leandro. Thanks for the implementation of pyFoldX.

I want to use it but I have problems running the notebook "Working with PDB Structures". 
Can you help me please?

I have a PC with windows10 and enabled windows susbsystem from linux to use any program in github by using the bash terminal. I get an academic license for FoldX (v5; Executable Foldx5 - Linux 64bits) and dowloaded the file to set the path to binary file into my my .bashrc. Next, i create a conda enviroment with pyton 3.8 called "foldX" and then run "pip install pyfoldx". Then, run a jupyter notebook following the tutorial "Working with PDB Structures" exactly with the same code and get this issue in the cell that contains the code "st.getTotalEnergy ()"

![image](https://user-images.githubusercontent.com/51969194/137219599-2ba9dd8f-8972-473e-854e-bd258bb75797.png)

what is the problem?

**Comment by miangoar** [comment]
Im so sorry!  ... rookie mistake. I solved my problem ! 
I'll put my mistake if it is useful for anyone.

When i downloaded the binary exec. of foldX, i got a file "foldx5Linux64.tar_.gz". Then i uncompress it using windows rar app and i thougth that the output file was the actuall binary. But not. I get confused by the extension ".tar_.gz" ,so, i renamed this file as "foldx5Linux64.tar" and the uncompress it and the outputs files include the real binary.

**Comment by leandroradusky** [comment]
Thanks for using pyFoldx and sharing :)

**Comment by miangoar** [comment]
Thank you too Leandro! 

Indeed i have a question. Can you help me please?

Is there an example of how to build an ensemeble from local PDB files? I have ~ 100 PDBs in my PC and yet not reached a way to build an esemble from my local files to compute it's energies.

The documentations shows how to build from Uniprot, but i want to do from my local files. To my undestand, first i have to build a Structure obj. per each one of my PDB files and then, add them to a Ensemble obj.  Or there is another easy way to do that?
