### ISSUE TITLE
BuildModel with more than one mutation

### ISSUE THREAD

**Issue by Ni-Ar** [leandroradusky/pyFoldX#3]
Hi @leandroradusky , 

I think _currently_ there's no way to run `.mutate()` with more than one different mutant.

For examples given a Structure object called `st` the following line works fine:

```python
energies, mu_st, wt_st = st.mutate("AC169F;", number_of_runs = 1 )
```
and it returns a `pd` data frame with one row:
```
energies.shape
(1, 22)
```
Where the one row corresponds to the ∆∆G values of that mutant and the columns are all the different energy components.

However the following constructs fail:

```python
energies, mu_st, wt_st = st.mutate(['AC169F,CC172P;', 'AC169F;', 'CC172P;'], number_of_runs = 1 )
```
as providing the mutants in a list returns this error:
```python
Computing mutation(s) ['AC169F,CC172P;', 'AC169F;', 'CC172P'] on target structure...

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-992011f5e234> in <module>
----> 1 energies, mu_st, wt_st = st.mutate(['AC169F,CC172P;', 'AC169F;', 'CC172P' ], number_of_runs = 1 )

~/software/miniconda/envs/pyfold/lib/python3.8/site-packages/pyfoldx/structure/structure.py in mutate(self, mutations, number_of_runs, terms, verbose)
    347         trajWT = Ensemble(self.code+"_WT",working_path="")
    348 
--> 349         ddGsDf, mutModels, wtModels = foldxHandler.getMutants(self, mutations, number_of_runs)
    350 
    351         # if generate mutated ensemble, add models to the ensemples

~/software/miniconda/envs/pyfold/lib/python3.8/site-packages/pyfoldx/foldx/foldxHandler.py in getMutants(st, mutations, number_of_runs, other_parameters)
    242     wtPdbs= []
    243     for i in range(number_of_runs):
--> 244         mutPdbs.append( structure.Structure(st.code+"_%s_%s" % (mutations.replace(",","_").replace(";",""),i),
    245                                             TMP_FOLDER+"tmp_1%s.pdb" % ("_"+str(i) if number_of_runs > 1 else "") ) )
    246         wtPdbs.append( structure.Structure("WT_"+st.code+"_%s_%s" % (mutations.replace(",","_").replace(";",""), i),

AttributeError: 'list' object has no attribute 'replace'
```
or if we provide the mutants not as a python list but as a character string:

```python
energies, mu_st, wt_st = st_AP1_Repaired.mutate('AC169F,CC172P;AC169F;CC172P;', number_of_runs = 1 )
```
it doesn't properly works as it returns only one mutant
```
energies.shape
(1, 22)
```
Lastly, when trying to construct the mutations as one would do in the [mutant file](http://foldxsuite.crg.eu/parameter/mutant-file) as in the "INDIVIDUAL LIST MODE", where the new line (`\n`) defines a different mutant, it also fails:

```python
energies, mu_st, wt_st = st_AP1_Repaired.mutate('AC169F,CC172P;\nAC169F;\nCC172P;', number_of_runs = 1 )
Computing mutation(s) AC169F,CC172P;
AC169F;
CC172P; on target structure...
Energy computed.
```

```python
energies.shape
(1, 22)
```

```python
energies.index
Index(['AP1_Repaired_AC169F_CC172P\nAC169F\nCC172P_0'], dtype='object')
```

I'm not sure if `pyFoldX` is still actively maintained, but it'd be awesome to fix this. Or maybe there's another workaround using for loops or similar?

**My personal comment**: 
In my opinion, as it stands, this packaged version of FoldX is truly awesome and way more user-friendly than the command line version of the tool. Especially all the text parsing that is happening under the hood makes using FoldX smooth, plus it's a way more modern piece of software to use. I just wish the small issues could be solved and a better documentation would be available.

**Comment by leandroradusky** [comment]
Hello @Ni-Ar. Thanks for pointing out this. PyFoldX is now in the process of being published, I'm the mantainer of the package and I'm doing one thing as a time. I will try to check & fix this ASAP. Meanwhile, I tell you the idea how: now the result of mutating a structure is another structure (and the energies and the wt), with several mutations, an Ensemble should be returned and this is not implemented. What I suggest you is that you run the mutations individually and store them in a list if you want to operate with them.
Best,
Leandro

**Comment by Ni-Ar** [comment]
Hi @leandroradusky thanks a lot for maintaining PyFoldX! I'll do the save the mutations in a list then.
Let me know if you need someone to test the new implementations. Good luck with the publication!

Nicco
