### ISSUE TITLE
How can i fix this error

### ISSUE THREAD

**Issue by abok2020** [leandroradusky/pyFoldX#4]
Sorry i am not an expert in linux. I keep getting an error - NameError: name 'exit' is not defined when i get to 'st.getTotalEnergy()'. This error is accompanied by 'FoldX executable not found, please set the variable FOLDX_LOCATION'. 
Thanks.

**Comment by leandroradusky** [comment]
Hi @abok2020,

You should execute `export FOLDX_BINARY=/your/path/to/foldx` or include it in your `.bashrc` file. Remember that you have to download foldx somewhere to be able to use pyfoldx.

Hope this helps, if not, let me know :)

**Comment by abok2020** [comment]
Thank you!. Will do that.

Jeremiah.
________________________________
